version: "3.8"
services:
  influxdb:
    image: influxdb:2.7.0
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin_idb
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin_idb
      - DOCKER_INFLUXDB_INIT_ORG=org_idb
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket_idb
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token_idb
      #- DOCKER_INFLUXDB_INIT_RETENTION
    ports:
      - "8086:8086"
    volumes:
      - influxdb_vol:/var/lib/influxdb

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    volumes:
      - grafana_vol:/var/lib/grafana
      #configuration and datasources
      - ./conf/grafana/:/etc/grafana/

volumes:
  influxdb_vol: {}
  grafana_vol: {}
