apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    basicAuth: true
    basicAuthUser: admin_idb
    jsonData:
      version: Flux
      organization: org_idb
      defaultBucket: bucket_idb
      tlsSkipVerify: true
    secureJsonData:
      basicAuthPassword: admin_idb
      token: token_idb
